--45394-EAC
CREATE INDEX IDXD_HISTLOGINS_USUARIO ON HIST_LOGINS (HIST_LO_USUARIO);

CREATE INDEX IDXD_HRELACIONADOS_CUENTA ON HIST_RELACIONADOS (HIST_RG_CUENTA);

DROP INDEX INDX_HIST_AL_USUARIO;
CREATE INDEX INDX_HIST_AL_USUARIO ON HIST_ALERTAS_GESTION (HIST_AL_USUARIO ASC, HIST_AL_DTECREADA DESC); 

