  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SC_SGC"."VI_INFORMACION_G1" ("PR_MC_COMENTARIO", "PR_MC_GRUPO", "PR_MC_EXPEDIENTE", "PR_MC_CLIENTE", "PR_MC_CREDITO"
, "PR_MC_PRODUCTO", "PR_MC_SUBPRODUCTO", "PR_MC_ESTATUS", "PR_MC_CODIGO", "PR_MC_RESULTADO", "PR_MC_ACCION", "PR_MC_UNIVERSO_CC", "PR_MC_MUESTRA_CC", "PR_MC_FECHA_CC", "PR_MC_TIPO_CC",
"PR_MC_DTEGESTION", "PR_MC_UASIGNADO", "PR_MC_UASIGNADO_ANT", "PR_MC_USUARIO", "PR_MC_DTEPCONTACTO", "PR_MC_NOGESTIONES",
"PR_MC_CODRELEV", "PR_MC_RESULTADORELEV", "PR_MC_DTERESULTADORELEV", "PR_MC_CODIGOVISITA", "PR_MC_RESULTADOV", "PR_MC_DTEVISITA", "PR_MC_NOVISITAS", "PR_MC_VISITADOR", "PR_MC_FILA",
"PR_MC_DTEFILA", "PR_MC_MODAL", "PR_MC_SECFILA", "PR_MC_MONTOPP", "PR_MC_DTEPP", "PR_MC_MTOUP", "PR_MC_DTEUP", "PR_MC_DTECARGAINI", "PR_MC_DTECARGA", "PR_MC_DTERETIRO", 
"PR_MC_AGENCIA", "PR_MC_DTEASIGNA", "PR_MC_DTEASIGNAV", "PR_MC_DTEASIGNAV_ANT", "PR_MC_DTEASIGNA_ANT", "PR_MC_CREDITOCONTACTADO", "PR_MC_DTECREDITOCONTACTADO",
"PR_MC_PRIMERAGESTION", "PR_MC_DTEPRIMERAGESTION", "PR_MC_UASIGNADOV", "PR_MC_UASIGNADOV_ANT", "PR_MC_DTEREACTIVA", "VI_SEMAFORO_GESTION", "VI_DIAS_SEMAFORO_GESTION",
"PR_MC_DESPACHOASIGNADO", "PR_MC_CAUSANOPAGO", "PR_MC_ID_FILA", "PR_MC_ESTATUSF", "PR_MC_NOPROMPARCIALES", "PR_MC_NOPROMNEGOCIACION", "PR_MC_NOPROMPARCUMP", 
"PR_MC_NOPROMNEGCUMP", "PR_MC_NOPROMPARINC", "PR_MC_NOPROMNEGINC", "PR_MC_MTOPAGOPAR", "PR_MC_MTOPAGOFALTANTEPAR", "PR_MC_MTOPAGONEG", "PR_MC_MTOPAGOFALTANTENEG", 
"PR_MC_MTOPAGOPARCUMP", "PR_MC_MTOPAGONEGCUMP", "PR_MC_NOMBRE", "PR_MC_CURP", "PR_MC_RFC", "PR_MC_CORREO", "PR_MC_INSTANCIA", "PR_MC_ESTATUS_PROMESA", 
"PR_MC_ESTATUS_PAGO", "PR_MC_INSTANCIAPREV", "PR_MC_IDREGLAASIG", "PR_MC_ZONA", "PR_MC_EXCLUSION", "PR_MC_LATITUD", "PR_MC_LONGITUD", "PR_MC_DTEASIGNAM", 
"PR_MC_DIASMORA_U", "PR_MC_SCORETOTAL", "PR_MC_ETIQUETA", "PR_CL_ACCOUNT_ID", "PR_CL_CUSTOM_DATA_91", "PR_CL_TIPODEPRODUCTO", "PR_CL_NOMBRE", 
"PR_CL_PHONE1", "PR_CL_PHONE2", "PR_CL_SECOND_ALT_PHO_NUMBER", "PR_CL_CREDIT_LIMIT", "PR_CL_CURRENT_BALANCE", "PR_CL_MONTO_VENCIDO", "PR_CL_MINIMUM_PAYMENT",
"PR_CL_AMOUNT_LAST_PAID", "PR_CL_CYCLE_NUMBER", "PR_CL_UTILIZACION", "PR_CL_BUCKET", "PR_CL_OVERLIMIT_AMOUNT", "PR_CL_ULTIMO_PAGO", "PR_CL_DATE_LAST_PURCHASE", 
"PR_CL_DATE_LAST_CASH_ADVANCE", "PR_CL_DATE_LAST_PAYMENT", "PR_CL_PHONE3", "PR_CL_CHRG_OFF_DT", "PR_CL_FEC_CORTE", "PR_CL_BURS", "PR_CL_SDO_CAPITAL",
"PR_CL_BK_MAX", "PR_CL_ADDRESS_LINE_1", "PR_CL_ADDRESS_LINE_2", "PR_CL_CITY", "PR_CL_POSTAL_CODE", "PR_CL_RISK_SCORE", "PR_CL_CUSTOMER_DATA_1",
"PR_CL_ORIGINACION", "PR_CL_FLP", "PR_CL_PAID_FULL_AMOUNT", "PR_CL_EMAIL_ADDRESS_LINE_1", "PR_CL_PAGO_INTENCION", "PR_CL_AMOUNT_FIXED_PAY", "PR_CL_AMT_CURR_1_30", 
"PR_CL_AMT_CURR_31_60", "PR_CL_AMT_CURR_61_90", "PR_CL_AMT_CURR_91_120", "PR_CL_PURCHASE_APR", "PR_CL_CASH_APR", "PR_CL_ID_CLIENTE", "PR_CL_PLAN", "PR_CL_RIESGO",
"PR_CL_DATE_LAST_PAY", "PR_CL_DATE_PAYMENT_DUE", "PR_CL_PAO", "PR_CL_BLOQUEO_PREV", "PR_CL_ROOT_FILE", "PR_CL_AM0C_DATE_STATEMENT", "PR_CL_AM0C_DATE_STATEMENT_2",
"PR_CL_AM0C_DATE_STATEMENT_3", "PR_CL_AM0C_DATE_STATEMENT_4", "PR_CL_AM0C_AMT_PAYMENTS", "PR_CL_AM0C_AMT_PAYMENTS_2", "PR_CL_AM0C_AMT_PAYMENTS_3",
"PR_CL_AM0C_AMT_PAYMENTS_4", "PR_CL_FLAG_LLAMADA", "PR_CL_FLAG_SMS", "PR_CL_FLAG_EMAIL", "PR_CL_FLAG_TTV", "PR_CL_MOTIVO_RECHAZO", "PR_CL_VARIABLE_SOFOM",
"PR_CL_TERMINACION", "PR_CL_FLAG_SALDO", "PR_CL_FLAG_MISC", "PR_CL_FLAG_PM", "PR_CL_FLAG_CIERRE", "PR_CL_FLAG_BLOQUEO", "PR_CL_FLAG_FRAUDE", "PR_CL_FLAG_DOC",
"PR_CL_FLAG_ST", "PR_CL_FLAG_T7", "PR_CL_FLAG_DISPUTA", "PR_CL_FLAG_BURS", "PR_CL_FLAG_BK", "PR_CL_FLAG_EMP", "PR_CL_FLAG_DEP", "PR_CL_FLAG_LN", "PR_CL_FLAG_PSC_PAGO",
"PR_CL_FLAG_PPAT", "PR_CL_FLAG_DEF", "PR_CL_FLAG_DOMI", "PR_CL_DATE_OPEN", "PR_CL_CUENTA_CLABE", "PR_CL_AVAILABLE_AMOUNT_BUY", "PR_CL_TANDEM", "PR_CL_TIPO_ENTRADA",
"PR_CL_NUMERO_CUENTAS_ABIERTAS", "PR_CL_TOTAL_SALDO_ACTUAL", "PR_CL_TOTAL_CREDITO_MAXIMO", "PR_CL_TOTAL_SALDO_VENCIDO", "PR_CL_PEOR_MOP", "PR_CL_TOTAL_LIMITE_CREDITO",
"PR_CL_NUMERO_MESES_ANTIGUEDAD", "PR_CL_TOTAL_PAGOS_EFECTUAR", "PR_CL_PEOR_MOP_REVOLVENTE", "PR_CL_LIMITE_MAXIMO_REVOLVENTE", "PR_CL_SCORE", "PR_CL_TIPO_PLAN",
"PR_CL_FEC_INI_TSYS", "PR_CL_FEC_FIN_TSYS", "PR_CL_TASA_PLAN", "PR_CL_EXPEDIENTE_MC") AS 
  SELECT
        NVL(PR_MC_COMENTARIO, ' ') PR_MC_COMENTARIO,
        NVL(PR_MC_GRUPO, 0) PR_MC_GRUPO,
        NVL(PR_MC_EXPEDIENTE, ' ') PR_MC_EXPEDIENTE,
        NVL(PR_MC_CLIENTE, ' ') PR_MC_CLIENTE,
        NVL(PR_MC_CREDITO, ' ') PR_MC_CREDITO,
        NVL(PR_MC_PRODUCTO, ' ') PR_MC_PRODUCTO,
        NVL(PR_MC_SUBPRODUCTO, ' ') PR_MC_SUBPRODUCTO,
        NVL(PR_MC_ESTATUS, ' ') PR_MC_ESTATUS,
        NVL(PR_MC_CODIGO, ' ') PR_MC_CODIGO,
        NVL(PR_MC_RESULTADO, ' ') PR_MC_RESULTADO,
        NVL(PR_MC_ACCION, ' ') PR_MC_ACCION,
        NVL(PR_MC_UNIVERSO_CC,' ') PR_MC_UNIVERSO_CC,
        NVL(PR_MC_MUESTRA_CC,' ') PR_MC_MUESTRA_CC,
	CASE 
            WHEN PR_MC_FECHA_CC IS NULL
                 OR TO_CHAR(PR_MC_FECHA_CC, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_FECHA_CC)
        END AS PR_MC_FECHA_CC,
        NVL(PR_MC_TIPO_CC,' ') PR_MC_TIPO_CC,
        CASE
            WHEN PR_MC_DTEGESTION IS NULL
                 OR TO_CHAR(PR_MC_DTEGESTION, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTEGESTION)
        END AS PR_MC_DTEGESTION,
        NVL(PR_MC_UASIGNADO, ' ') PR_MC_UASIGNADO,
        NVL(PR_MC_UASIGNADO_ANT, ' ') PR_MC_UASIGNADO_ANT,
        NVL(PR_MC_USUARIO, ' ') PR_MC_USUARIO,
        CASE
            WHEN PR_MC_DTEPCONTACTO IS NULL
                 OR TO_CHAR(PR_MC_DTEPCONTACTO, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTEPCONTACTO)
        END AS PR_MC_DTEPCONTACTO,
        NVL(PR_MC_NOGESTIONES, 0) PR_MC_NOGESTIONES,
        NVL(PR_MC_CODRELEV, ' ') PR_MC_CODRELEV,
        NVL(PR_MC_RESULTADORELEV, ' ') PR_MC_RESULTADORELEV,
        CASE
            WHEN PR_MC_DTERESULTADORELEV IS NULL
                 OR TO_CHAR(PR_MC_DTERESULTADORELEV, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTERESULTADORELEV)
        END AS PR_MC_DTERESULTADORELEV,
        NVL(PR_MC_CODIGOVISITA, ' ') PR_MC_CODIGOVISITA,
        NVL(PR_MC_RESULTADOV, ' ') PR_MC_RESULTADOV,
        CASE
            WHEN PR_MC_DTEVISITA IS NULL
                 OR TO_CHAR(PR_MC_DTEVISITA, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTEVISITA)
        END AS PR_MC_DTEVISITA,
        NVL(PR_MC_NOVISITAS, 0) PR_MC_NOVISITAS,
        NVL(PR_MC_VISITADOR, ' ') PR_MC_VISITADOR,
        NVL(PR_MC_FILA, ' ') PR_MC_FILA,
        CASE
            WHEN PR_MC_DTEFILA IS NULL
                 OR TO_CHAR(PR_MC_DTEFILA, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTEFILA)
        END AS PR_MC_DTEFILA,
        NVL(PR_MC_MODAL, 0) PR_MC_MODAL,
        NVL(PR_MC_SECFILA, 0) PR_MC_SECFILA,
        NVL(PR_MC_MONTOPP, 0) PR_MC_MONTOPP,
        CASE
            WHEN PR_MC_DTEPP IS NULL
                 OR TO_CHAR(PR_MC_DTEPP, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTEPP)
        END AS PR_MC_DTEPP,
        NVL(PR_MC_MTOUP, 0) PR_MC_MTOUP,
        CASE
            WHEN PR_MC_DTEUP IS NULL
                 OR TO_CHAR(PR_MC_DTEUP, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTEUP)
        END AS PR_MC_DTEUP,
        CASE
            WHEN PR_MC_DTECARGAINI IS NULL
                 OR TO_CHAR(PR_MC_DTECARGAINI, 'DD/MM/YYYY') = '01/01/1900' THEN

                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTECARGAINI)
        END AS PR_MC_DTECARGAINI,
        CASE
            WHEN PR_MC_DTECARGA IS NULL
                 OR TO_CHAR(PR_MC_DTECARGA, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTECARGA)
        END AS PR_MC_DTECARGA,
        CASE
            WHEN PR_MC_DTERETIRO IS NULL
                 OR TO_CHAR(PR_MC_DTERETIRO, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTERETIRO)
        END AS PR_MC_DTERETIRO,
        NVL(PR_MC_AGENCIA, 0) PR_MC_AGENCIA,
        CASE
            WHEN PR_MC_DTEASIGNA IS NULL
                 OR TO_CHAR(PR_MC_DTEASIGNA, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTEASIGNA)
        END AS PR_MC_DTEASIGNA,
        CASE
            WHEN PR_MC_DTEASIGNAV IS NULL
                 OR TO_CHAR(PR_MC_DTEASIGNAV, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTEASIGNAV)
        END AS PR_MC_DTEASIGNAV,
        CASE
            WHEN PR_MC_DTEASIGNAV_ANT IS NULL
                 OR TO_CHAR(PR_MC_DTEASIGNAV_ANT, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTEASIGNAV_ANT)
        END AS PR_MC_DTEASIGNAV_ANT,
        CASE
            WHEN PR_MC_DTEASIGNA_ANT IS NULL
                 OR TO_CHAR(PR_MC_DTEASIGNA_ANT, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTEASIGNA_ANT)
        END AS PR_MC_DTEASIGNA_ANT,
        NVL(PR_MC_CREDITOCONTACTADO, 0) PR_MC_CREDITOCONTACTADO,
        CASE
            WHEN PR_MC_DTECREDITOCONTACTADO IS NULL
                 OR TO_CHAR(PR_MC_DTECREDITOCONTACTADO, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTECREDITOCONTACTADO)
        END AS PR_MC_DTECREDITOCONTACTADO,
        NVL(PR_MC_PRIMERAGESTION, ' ') PR_MC_PRIMERAGESTION,
        CASE
            WHEN PR_MC_DTEPRIMERAGESTION IS NULL
                 OR TO_CHAR(PR_MC_DTEPRIMERAGESTION, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTEPRIMERAGESTION)
        END AS PR_MC_DTEPRIMERAGESTION,
        NVL(PR_MC_UASIGNADOV, ' ') PR_MC_UASIGNADOV,
        NVL(PR_MC_UASIGNADOV_ANT, ' ') PR_MC_UASIGNADOV_ANT,
        CASE
            WHEN PR_MC_DTEREACTIVA IS NULL
                 OR TO_CHAR(PR_MC_DTEREACTIVA, 'DD/MM/YYYY') = '01/01/1900' THEN

                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTEREACTIVA)
        END AS PR_MC_DTEREACTIVA,
        (
            CASE
                WHEN ROUND(SYSDATE - PR_MC_DTEGESTION) <= (
                    SELECT
                        CAT_CO_VERDE
                    FROM
                        CAT_CODIGOS
                    WHERE
                        NVL(CAT_CO_ACCION, '')
                        || NVL(CAT_CO_RESULTADO, '') = NVL(PR_MC_CODIGO, '')
                ) THEN
                    'VERDE'
                WHEN ROUND(SYSDATE - PR_MC_DTEGESTION) < (
                    SELECT
                        CAT_CO_AMARILLO
                    FROM
                        CAT_CODIGOS
                    WHERE
                        NVL(CAT_CO_ACCION, '')
                        || NVL(CAT_CO_RESULTADO, '') = NVL(PR_MC_CODIGO, '')
                ) THEN
                    'AMARILLO'
                ELSE
                    'ROJO'
            END
        ) AS VI_SEMAFORO_GESTION,
        (
            CASE
                WHEN ROUND(SYSDATE - PR_MC_DTEGESTION) <= (
                    SELECT
                        CAT_CO_VERDE
                    FROM
                        CAT_CODIGOS
                    WHERE
                        NVL(CAT_CO_ACCION, '')
                        || NVL(CAT_CO_RESULTADO, '') = NVL(PR_MC_CODIGO, '')
                ) THEN
                    ( ABS(ROUND((SYSDATE - PR_MC_DTEGESTION) -(
                        SELECT
                            CAT_CO_AMARILLO
                        FROM
                            CAT_CODIGOS
                        WHERE
                            NVL(CAT_CO_ACCION, '')
                            || NVL(CAT_CO_RESULTADO, '') = NVL(PR_MC_CODIGO, '')

                    ))) )
                    || ' d�as para cambiar a semaforo amarillo'
                WHEN ROUND(SYSDATE - PR_MC_DTEGESTION) > (
                    SELECT
                        CAT_CO_VERDE
                    FROM
                        CAT_CODIGOS
                    WHERE
                        NVL(CAT_CO_ACCION, '')
                        || NVL(CAT_CO_RESULTADO, '') = NVL(PR_MC_CODIGO, '')
                )
                     AND ROUND(SYSDATE - PR_MC_DTEGESTION) < (
                    SELECT
                        CAT_CO_AMARILLO
                    FROM
                        CAT_CODIGOS
                    WHERE
                        NVL(CAT_CO_ACCION, '')
                        || NVL(CAT_CO_RESULTADO, '') = NVL(PR_MC_CODIGO, '')
                ) THEN
                    ( ABS(ROUND((SYSDATE - PR_MC_DTEGESTION) -(
                        SELECT
                            CAT_CO_AMARILLO
                        FROM
                            CAT_CODIGOS
                        WHERE
                            NVL(CAT_CO_ACCION, '')
                            || NVL(CAT_CO_RESULTADO, '') = NVL(PR_MC_CODIGO, '')

                    ))) )
                    || ' d�as para cambiar a semaforo rojo'
                ELSE
                    'Cr�dito sin gesti�n o gestionado hace m�s de '
                    || NVL((
                        SELECT
                            CAT_CO_AMARILLO
                        FROM
                            CAT_CODIGOS
                        WHERE
                            NVL(CAT_CO_ACCION, '')
                            || NVL(CAT_CO_RESULTADO, '') = NVL(PR_MC_CODIGO, '')

                    ), ABS(TRUNC(PR_MC_DTEASIGNA) - TRUNC(SYSDATE)))
                    || ' dias'
            END
        ) AS VI_DIAS_SEMAFORO_GESTION,
        NVL(PR_MC_DESPACHOASIGNADO, ' ') PR_MC_DESPACHOASIGNADO,
        NVL(PR_MC_CAUSANOPAGO, ' ') PR_MC_CAUSANOPAGO,
        NVL(PR_MC_ID_FILA, 0) PR_MC_ID_FILA,
        NVL(PR_MC_ESTATUSF, 0) PR_MC_ESTATUSF,
        NVL(PR_MC_NOPROMPARCIALES, 0) PR_MC_NOPROMPARCIALES,
        NVL(PR_MC_NOPROMNEGOCIACION, 0) PR_MC_NOPROMNEGOCIACION,
        NVL(PR_MC_NOPROMPARCUMP, 0) PR_MC_NOPROMPARCUMP,
        NVL(PR_MC_NOPROMNEGCUMP, 0) PR_MC_NOPROMNEGCUMP,
        NVL(PR_MC_NOPROMPARINC, 0) PR_MC_NOPROMPARINC,
        NVL(PR_MC_NOPROMNEGINC, 0) PR_MC_NOPROMNEGINC,
        NVL(PR_MC_MTOPAGOPAR, 0) PR_MC_MTOPAGOPAR,
        NVL(PR_MC_MTOPAGOFALTANTEPAR, 0) PR_MC_MTOPAGOFALTANTEPAR,
        NVL(PR_MC_MTOPAGONEG, 0) PR_MC_MTOPAGONEG,
        NVL(PR_MC_MTOPAGOFALTANTENEG, 0) PR_MC_MTOPAGOFALTANTENEG,
        NVL(PR_MC_MTOPAGOPARCUMP, 0) PR_MC_MTOPAGOPARCUMP,
        NVL(PR_MC_MTOPAGONEGCUMP, 0) PR_MC_MTOPAGONEGCUMP,
        NVL(PR_MC_NOMBRE, ' ') PR_MC_NOMBRE,
        NVL(PR_MC_CURP, ' ') PR_MC_CURP,
        NVL(PR_MC_RFC, ' ') PR_MC_RFC,
        NVL(PR_MC_CORREO, ' ') PR_MC_CORREO,
        NVL(PR_MC_INSTANCIA, ' ') PR_MC_INSTANCIA,
        NVL(PR_MC_ESTATUS_PROMESA, ' ') PR_MC_ESTATUS_PROMESA,
        NVL(PR_MC_ESTATUS_PAGO, ' ') PR_MC_ESTATUS_PAGO,
        NVL(PR_MC_INSTANCIAPREV, ' ') PR_MC_INSTANCIAPREV,
        NVL(PR_MC_IDREGLAASIG, 0) PR_MC_IDREGLAASIG,
        NVL(PR_MC_ZONA, ' ') PR_MC_ZONA,
        NVL(PR_MC_EXCLUSION, 0) PR_MC_EXCLUSION,
        NVL(PR_MC_LATITUD, ' ') PR_MC_LATITUD,
        NVL(PR_MC_LONGITUD, ' ') PR_MC_LONGITUD,
        CASE
            WHEN PR_MC_DTEASIGNAM IS NULL
                 OR TO_CHAR(PR_MC_DTEASIGNAM, 'DD/MM/YYYY') = '01/01/1900' THEN
                TO_DATE('01/01/1900')
            ELSE
                TO_DATE(PR_MC_DTEASIGNAM)
        END AS PR_MC_DTEASIGNAM,
        NVL(PR_MC_DIASMORA_U, 0) PR_MC_DIASMORA_U,
        NVL(PR_MC_SCORETOTAL, 0) PR_MC_SCORETOTAL,
        NVL(PR_MC_ETIQUETA, ' ') PR_MC_ETIQUETA,
        NVL(PR_CL_ACCOUNT_ID,' ') PR_CL_ACCOUNT_ID
        ,NVL(PR_CL_CUSTOM_DATA_91,' ') PR_CL_CUSTOM_DATA_91
        ,NVL(PR_CL_TIPODEPRODUCTO,' ') PR_CL_TIPODEPRODUCTO
        ,NVL(PR_CL_NOMBRE,' ') PR_CL_NOMBRE
        ,NVL(PR_CL_PHONE1,' ') PR_CL_PHONE1
        ,NVL(PR_CL_PHONE2,' ') PR_CL_PHONE2
        ,NVL(PR_CL_SECOND_ALT_PHO_NUMBER,' ') PR_CL_SECOND_ALT_PHO_NUMBER
        ,NVL(PR_CL_CREDIT_LIMIT,0) PR_CL_CREDIT_LIMIT
        ,NVL(PR_CL_CURRENT_BALANCE,0) PR_CL_CURRENT_BALANCE
        ,NVL(PR_CL_MONTO_VENCIDO,0) PR_CL_MONTO_VENCIDO
        ,NVL(PR_CL_MINIMUM_PAYMENT,0) PR_CL_MINIMUM_PAYMENT
        ,NVL(PR_CL_AMOUNT_LAST_PAID,0) PR_CL_AMOUNT_LAST_PAID
        ,NVL(PR_CL_CYCLE_NUMBER,0) PR_CL_CYCLE_NUMBER
        ,NVL(PR_CL_UTILIZACION,0) PR_CL_UTILIZACION
        ,NVL(PR_CL_BUCKET,0) PR_CL_BUCKET
        ,NVL(PR_CL_OVERLIMIT_AMOUNT,0) PR_CL_OVERLIMIT_AMOUNT
        ,CASE  WHEN PR_CL_ULTIMO_PAGO IS NULL  OR TO_CHAR(PR_CL_ULTIMO_PAGO , 'DD/MM/YYYY') = '01/01/1900' THEN  TO_DATE('01/01/1900')  
        ELSE  TO_DATE(PR_CL_ULTIMO_PAGO)  END AS PR_CL_ULTIMO_PAGO
        ,CASE  WHEN PR_CL_DATE_LAST_PURCHASE IS NULL  OR TO_CHAR(PR_CL_DATE_LAST_PURCHASE , 'DD/MM/YYYY') = '01/01/1900' THEN  TO_DATE('01/01/1900') 
        ELSE  TO_DATE(PR_CL_DATE_LAST_PURCHASE)  END AS PR_CL_DATE_LAST_PURCHASE
        ,CASE  WHEN PR_CL_DATE_LAST_CASH_ADVANCE IS NULL  OR TO_CHAR(PR_CL_DATE_LAST_CASH_ADVANCE , 'DD/MM/YYYY') = '01/01/1900' 
        THEN  TO_DATE('01/01/1900')  ELSE  TO_DATE(PR_CL_DATE_LAST_CASH_ADVANCE)  END AS PR_CL_DATE_LAST_CASH_ADVANCE
        ,CASE  WHEN PR_CL_DATE_LAST_PAYMENT IS NULL  OR TO_CHAR(PR_CL_DATE_LAST_PAYMENT , 'DD/MM/YYYY') = '01/01/1900' THEN  TO_DATE('01/01/1900')  
        ELSE  TO_DATE(PR_CL_DATE_LAST_PAYMENT)  END AS PR_CL_DATE_LAST_PAYMENT
        ,NVL(PR_CL_PHONE3,' ') PR_CL_PHONE3
        ,NVL(PR_CL_CHRG_OFF_DT,' ') PR_CL_CHRG_OFF_DT
        ,CASE  WHEN PR_CL_FEC_CORTE IS NULL  OR TO_CHAR(PR_CL_FEC_CORTE , 'DD/MM/YYYY') = '01/01/1900' 
        THEN  TO_DATE('01/01/1900')  ELSE  TO_DATE(PR_CL_FEC_CORTE)  END AS PR_CL_FEC_CORTE
        ,NVL(PR_CL_BURS,' ') PR_CL_BURS
        ,NVL(PR_CL_SDO_CAPITAL,0) PR_CL_SDO_CAPITAL
        ,NVL(PR_CL_BK_MAX,0) PR_CL_BK_MAX
        ,NVL(PR_CL_ADDRESS_LINE_1,' ') PR_CL_ADDRESS_LINE_1
        ,NVL(PR_CL_ADDRESS_LINE_2,' ') PR_CL_ADDRESS_LINE_2
        ,NVL(PR_CL_CITY,' ') PR_CL_CITY
        ,NVL(PR_CL_POSTAL_CODE,' ') PR_CL_POSTAL_CODE
        ,NVL(PR_CL_RISK_SCORE,' ') PR_CL_RISK_SCORE
        ,NVL(PR_CL_CUSTOMER_DATA_1,' ') PR_CL_CUSTOMER_DATA_1
        ,NVL(PR_CL_ORIGINACION,' ') PR_CL_ORIGINACION
        ,CASE  WHEN PR_CL_FLP IS NULL  OR TO_CHAR(PR_CL_FLP , 'DD/MM/YYYY') = '01/01/1900' THEN  TO_DATE('01/01/1900')  
        ELSE  TO_DATE(PR_CL_FLP)  END AS PR_CL_FLP
        ,NVL(PR_CL_PAID_FULL_AMOUNT,0) PR_CL_PAID_FULL_AMOUNT
        ,NVL(PR_CL_EMAIL_ADDRESS_LINE_1,' ') PR_CL_EMAIL_ADDRESS_LINE_1
        ,NVL(PR_CL_PAGO_INTENCION,' ') PR_CL_PAGO_INTENCION
        ,NVL(PR_CL_AMOUNT_FIXED_PAY,0) PR_CL_AMOUNT_FIXED_PAY
        ,NVL(PR_CL_AMT_CURR_1_30,0) PR_CL_AMT_CURR_1_30
        ,NVL(PR_CL_AMT_CURR_31_60,0) PR_CL_AMT_CURR_31_60
        ,NVL(PR_CL_AMT_CURR_61_90,0) PR_CL_AMT_CURR_61_90
        ,NVL(PR_CL_AMT_CURR_91_120,0) PR_CL_AMT_CURR_91_120
        ,NVL(PR_CL_PURCHASE_APR,0) PR_CL_PURCHASE_APR
        ,NVL(PR_CL_CASH_APR,0) PR_CL_CASH_APR
        ,NVL(PR_CL_ID_CLIENTE,' ') PR_CL_ID_CLIENTE
        ,NVL(PR_CL_PLAN,' ') PR_CL_PLAN
        ,NVL(PR_CL_RIESGO,' ') PR_CL_RIESGO
        ,CASE  WHEN PR_CL_DATE_LAST_PAY IS NULL  OR TO_CHAR(PR_CL_DATE_LAST_PAY , 'DD/MM/YYYY') = '01/01/1900' 
        THEN  TO_DATE('01/01/1900')  ELSE  TO_DATE(PR_CL_DATE_LAST_PAY)  END AS PR_CL_DATE_LAST_PAY
        ,CASE  WHEN PR_CL_DATE_PAYMENT_DUE IS NULL  OR TO_CHAR(PR_CL_DATE_PAYMENT_DUE , 'DD/MM/YYYY') = '01/01/1900' 
        THEN  TO_DATE('01/01/1900')  ELSE  TO_DATE(PR_CL_DATE_PAYMENT_DUE)  END AS PR_CL_DATE_PAYMENT_DUE
        ,NVL(PR_CL_PAO,' ') PR_CL_PAO
        ,NVL(PR_CL_BLOQUEO_PREV,' ') PR_CL_BLOQUEO_PREV
        ,NVL(PR_CL_ROOT_FILE,' ') PR_CL_ROOT_FILE
        ,CASE  WHEN PR_CL_AM0C_DATE_STATEMENT IS NULL  OR TO_CHAR(PR_CL_AM0C_DATE_STATEMENT , 'DD/MM/YYYY') = '01/01/1900' 
        THEN  TO_DATE('01/01/1900')  ELSE  TO_DATE(PR_CL_AM0C_DATE_STATEMENT)  END AS PR_CL_AM0C_DATE_STATEMENT
        ,CASE  WHEN PR_CL_AM0C_DATE_STATEMENT_2 IS NULL  OR TO_CHAR(PR_CL_AM0C_DATE_STATEMENT_2 , 'DD/MM/YYYY') = '01/01/1900' 
        THEN  TO_DATE('01/01/1900')  ELSE
  TO_DATE(PR_CL_AM0C_DATE_STATEMENT_2)  END AS PR_CL_AM0C_DATE_STATEMENT_2
        ,CASE  WHEN PR_CL_AM0C_DATE_STATEMENT_3 IS NULL  OR TO_CHAR(PR_CL_AM0C_DATE_STATEMENT_3 , 'DD/MM/YYYY') = '01/01/1900' 
        THEN  TO_DATE('01/01/1900')  ELSE
  TO_DATE(PR_CL_AM0C_DATE_STATEMENT_3)  END AS PR_CL_AM0C_DATE_STATEMENT_3
        ,CASE  WHEN PR_CL_AM0C_DATE_STATEMENT_4 IS NULL  OR TO_CHAR(PR_CL_AM0C_DATE_STATEMENT_4 , 'DD/MM/YYYY') = '01/01/1900' 
        THEN  TO_DATE('01/01/1900')  ELSE
  TO_DATE(PR_CL_AM0C_DATE_STATEMENT_4)  END AS PR_CL_AM0C_DATE_STATEMENT_4
        ,NVL(PR_CL_AM0C_AMT_PAYMENTS,0) PR_CL_AM0C_AMT_PAYMENTS
        ,NVL(PR_CL_AM0C_AMT_PAYMENTS_2,0) PR_CL_AM0C_AMT_PAYMENTS_2
        ,NVL(PR_CL_AM0C_AMT_PAYMENTS_3,0) PR_CL_AM0C_AMT_PAYMENTS_3
        ,NVL(PR_CL_AM0C_AMT_PAYMENTS_4,0) PR_CL_AM0C_AMT_PAYMENTS_4
        ,NVL(PR_CL_FLAG_LLAMADA,' ') PR_CL_FLAG_LLAMADA
        ,NVL(PR_CL_FLAG_SMS,' ') PR_CL_FLAG_SMS
        ,NVL(PR_CL_FLAG_EMAIL,' ') PR_CL_FLAG_EMAIL
        ,NVL(PR_CL_FLAG_TTV,' ') PR_CL_FLAG_TTV
        ,NVL(PR_CL_MOTIVO_RECHAZO,' ') PR_CL_MOTIVO_RECHAZO
        ,NVL(PR_CL_VARIABLE_SOFOM,' ') PR_CL_VARIABLE_SOFOM
        ,NVL(PR_CL_TERMINACION,' ') PR_CL_TERMINACION
        ,NVL(PR_CL_FLAG_SALDO,' ') PR_CL_FLAG_SALDO
        ,NVL(PR_CL_FLAG_MISC,' ') PR_CL_FLAG_MISC
        ,NVL(PR_CL_FLAG_PM,' ') PR_CL_FLAG_PM
        ,NVL(PR_CL_FLAG_CIERRE,' ') PR_CL_FLAG_CIERRE
        ,NVL(PR_CL_FLAG_BLOQUEO,' ') PR_CL_FLAG_BLOQUEO
        ,NVL(PR_CL_FLAG_FRAUDE,' ') PR_CL_FLAG_FRAUDE
        ,NVL(PR_CL_FLAG_DOC,' ') PR_CL_FLAG_DOC
        ,NVL(PR_CL_FLAG_ST,' ') PR_CL_FLAG_ST
        ,NVL(PR_CL_FLAG_T7,' ') PR_CL_FLAG_T7
        ,NVL(PR_CL_FLAG_DISPUTA,' ') PR_CL_FLAG_DISPUTA
        ,NVL(PR_CL_FLAG_BURS,' ') PR_CL_FLAG_BURS
        ,NVL(PR_CL_FLAG_BK,' ') PR_CL_FLAG_BK
        ,NVL(PR_CL_FLAG_EMP,' ') PR_CL_FLAG_EMP
        ,NVL(PR_CL_FLAG_DEP,' ') PR_CL_FLAG_DEP
        ,NVL(PR_CL_FLAG_LN,' ') PR_CL_FLAG_LN
        ,NVL(PR_CL_FLAG_PSC_PAGO,' ') PR_CL_FLAG_PSC_PAGO
        ,NVL(PR_CL_FLAG_PPAT,' ') PR_CL_FLAG_PPAT
        ,NVL(PR_CL_FLAG_DEF,' ') PR_CL_FLAG_DEF
        ,NVL(PR_CL_FLAG_DOMI,' ') PR_CL_FLAG_DOMI
        ,CASE  WHEN PR_CL_DATE_OPEN IS NULL  OR TO_CHAR(PR_CL_DATE_OPEN , 'DD/MM/YYYY') = '01/01/1900' THEN  TO_DATE('01/01/1900')  
        ELSE  TO_DATE(PR_CL_DATE_OPEN)  END AS PR_CL_DATE_OPEN
        ,NVL(PR_CL_CUENTA_CLABE,' ') PR_CL_CUENTA_CLABE
        ,NVL(PR_CL_AVAILABLE_AMOUNT_BUY,0) PR_CL_AVAILABLE_AMOUNT_BUY
        ,NVL(PR_CL_TANDEM,' ') PR_CL_TANDEM
        ,NVL(PR_CL_TIPO_ENTRADA,' ') PR_CL_TIPO_ENTRADA
        ,NVL(PR_CL_NUMERO_CUENTAS_ABIERTAS,0) PR_CL_NUMERO_CUENTAS_ABIERTAS
        ,NVL(PR_CL_TOTAL_SALDO_ACTUAL,0) PR_CL_TOTAL_SALDO_ACTUAL
        ,NVL(PR_CL_TOTAL_CREDITO_MAXIMO,0) PR_CL_TOTAL_CREDITO_MAXIMO
        ,NVL(PR_CL_TOTAL_SALDO_VENCIDO,0) PR_CL_TOTAL_SALDO_VENCIDO
        ,NVL(PR_CL_PEOR_MOP,0) PR_CL_PEOR_MOP
        ,NVL(PR_CL_TOTAL_LIMITE_CREDITO,0) PR_CL_TOTAL_LIMITE_CREDITO
        ,NVL(PR_CL_NUMERO_MESES_ANTIGUEDAD,0) PR_CL_NUMERO_MESES_ANTIGUEDAD
        ,NVL(PR_CL_TOTAL_PAGOS_EFECTUAR,0) PR_CL_TOTAL_PAGOS_EFECTUAR
        ,NVL(PR_CL_PEOR_MOP_REVOLVENTE,0) PR_CL_PEOR_MOP_REVOLVENTE
        ,NVL(PR_CL_LIMITE_MAXIMO_REVOLVENTE,0) PR_CL_LIMITE_MAXIMO_REVOLVENTE
        ,NVL(PR_CL_SCORE,0) PR_CL_SCORE
        ,NVL(PR_CL_TIPO_PLAN,' ') PR_CL_TIPO_PLAN
        ,CASE  WHEN PR_CL_FEC_INI_TSYS IS NULL  OR TO_CHAR(PR_CL_FEC_INI_TSYS , 'DD/MM/YYYY') = '01/01/1900' THEN  TO_DATE('01/01/1900')  
        ELSE  TO_DATE(PR_CL_FEC_INI_TSYS)  END AS PR_CL_FEC_INI_TSYS
        ,CASE  WHEN PR_CL_FEC_FIN_TSYS IS NULL  OR TO_CHAR(PR_CL_FEC_FIN_TSYS ,'DD/MM/YYYY') = '01/01/1900' THEN  TO_DATE('01/01/1900') 
        ELSE  TO_DATE(PR_CL_FEC_FIN_TSYS)  END AS PR_CL_FEC_FIN_TSYS
        ,NVL(PR_CL_TASA_PLAN,0) PR_CL_TASA_PLAN
        ,NVL(PR_CL_EXPEDIENTE_MC,' ') PR_CL_EXPEDIENTE_MC
    FROM
        PR_MC_GRAL
        JOIN PR_CLIENTE ON PR_MC_EXPEDIENTE = PR_CL_EXPEDIENTE_MC